# Generated by Django 3.2.5 on 2021-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("emp_id", models.CharField(max_length=10, unique=True)),
                ("location", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=12)),
                ("email_id", models.EmailField(max_length=50)),
                ("joining_date", models.DateField()),
                ("last_date", models.DateField(blank=True)),
            ],
            options={
                "db_table": "Employee Data",
            },
        ),
    ]
