# Generated by Django 3.2.5 on 2021-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
