# Generated by Django 3.2.5 on 2021-07-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_auto_20210725_0241"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="Employee_Data",
        ),
    ]
