# Generated by Django 3.2.5 on 2021-07-25 13:53

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("db", "0004_alter_employee_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[("admin", "admin"), ("simple_user", "simple_user")],
                        default="simple_user",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "user_table",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
